name: getstartuptees
favicon: null
layout_spectrum: 0.9474993224721402
typography_spectrum: 0.6221216500271112
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.19147885777056217
  lightness: 0.8551687619183213
  saturation: 0.4573698171880096
  rhythmicContrast: 0.7046036515384912
purpose: []
